### ISSUE TITLE
Hello! When will you release your code?

### ISSUE THREAD

**Issue by Zera-Algorithm** [ASTERISC-Release/HitchHiker#1]
I greatly admire the research work you have done in your paper and am very excited about your findings. I firmly believe that the code you used will be of immense help to my research. I would greatly appreciate it if you could share the relevant code, as it would assist me in better understanding and applying your research results. Thank you for considering my request, and I look forward to your response!

**Comment by Icegrave0391** [comment]
Hi! Thanks for your interest, and sorry for the delay.

I’ve been busy with deadlines recently, but I’ll clean up and release the code by this week. :)

**Comment by Zera-Algorithm** [comment]
Thanks! Looking forward to your brilliant code.
